site_name: pyKilt
site_description: Kinetic Inverse-Laplace Toolbox (KILT) for fluorescence lifetime analysis
repo_url: https://github.com/AdrienR09/pyKilt
repo_name: pyKilt

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest

nav:
  - Home: index.md
  - Installation: installation.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          # Tell mkdocstrings where to import your package from
          paths: ["."]
          options:
            # pick one: "numpy" or "google"
            docstring_style: numpy
            show_source: false
            show_signature: true
            separate_signature: true
            show_root_heading: true
            members_order: source
            filters: ["!^_"]   # hide private members

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist
