name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings[python]
          # Install your package so mkdocstrings can import it
          pip install -e .

      - name: Build & deploy docs
        run: mkdocs gh-deploy --force
